set(handles.axes33,'visible','off')
set(handles.axes40,'visible','off')
set(handles.axes41,'visible','off')
set(handles.text112,'Visible','off')
set(handles.text113,'Visible','off')
set(handles.exclch,'visible','off')
set(handles.text103,'visible','off')
set(handles.text104,'visible','off')
set(handles.text105,'visible','off')
set(handles.specch,'visible','off')
set(handles.speccall,'visible','off')
set(handles.uipanel3,'visible','off')

set(handles.uipanel4,'visible','off')