function Hd = high_pass
%HIGH_PASS Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.8 and the Signal Processing Toolbox 6.11.
%
% Generated on: 07-Jan-2010 10:09:34
%

% Butterworth Highpass filter designed using the BUTTER function.

% All frequency values are in Hz.
Fs = 194162;  % Sampling Frequency

N  = 5;     % Order
Fc = 5000;  % Cutoff Frequency

% Calculate the zpk values using the BUTTER function.
[z,p,k] = butter(N, Fc/(Fs/2), 'high');

% To avoid round-off errors, do not use the transfer function.  Instead
% get the zpk representation and convert it to second-order sections.
[sos_var,g] = zp2sos(z, p, k);
Hd          = dfilt.df2sos(sos_var, g);

% [EOF]
